version: '3'

services:
  master:
    image: redis:5.0
    hostname: redis-master
    container_name: redis-master
    command: redis-server --replica-announce-ip redis-master --replica-announce-port 6379 
    network_mode: host
  slave-1:
    image: redis:5.0
    hostname: redis-slave-1
    container_name: redis-slave-1
    command: redis-server --slaveof redis-master 6379 --replica-announce-ip redis-slave-1 --replica-announce-port 6380
  slave-2:
    image: redis:5.0
    hostname: redis-slave-2
    container_name: redis-slave-2
    command: redis-server --slaveof redis-master 6379 --replica-announce-ip redis-slave-2 --replica-announce-port 6381
